version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build
      - run: dotnet pack Aleatory.Library/Aleatory.Library.csproj --configuration Release -p:JobId=${CIRCLE_BUILD_NUM}
      - run: dotnet nuget push Aleatory.Library/bin/Release/*.nupkg -k ${NugetApiKey} -s https://api.nuget.org/v3/index.json